add Url VO & UrlValidator
2DSharp/Phypes pull request #10
Opened 2018-10-20 18:02 UTC by angyvolin

2018-10-20 20:06 UTC, 2DSharp requested changes
The test fails on using non-http based urls, for example `ftp://`. Needs fixing.

2018-10-21 07:03 UTC, 2DSharp commented
Also, is there a specific reason for not using `filter_var` for validating the URL?

2018-10-21 10:16 UTC, angyvolin commented
> Also, is there a specific reason for not using `filter_var` for validating the URL?

https://d-mueller.de/blog/why-url-validation-with-filter_var-might-not-be-a-good-idea/

2018-10-21 11:57 UTC, 2DSharp commented
You seem to have copied the code from `Symfony/UrlValidator` (https://github.com/symfony/Validator/blob/master/Constraints/UrlValidator.php). Symfony operates under the MIT license. Please add the license for this, here are some suggestions: https://softwareengineering.stackexchange.com/questions/297217/using-code-under-apache-2-0-license-in-my-program-using-mit-license

2018-10-21 12:04 UTC, 2DSharp approved these changes

2018-10-21 12:07 UTC, 2DSharp requested changes

2018-10-21 12:07 UTC, 2DSharp commented on tests/UnitTests/Validator/UrlValidatorTest.php
>              ],
Please add some more tests on invalid values from https://d-mueller.de/blog/why-url-validation-with-filter_var-might-not-be-a-good-idea/

2019-01-26 09:40 UTC, closed without merging